apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  path: "./deploy/nginxapp"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
